### ISSUE TITLE
Remove alerts

### ISSUE THREAD

**Issue by KniteenK** [KniteenK/Q-gpt-frontend#22]
Remove alerts from everywhere and use valid type of notification , eg - toast

**Comment by Niketiiitd** [comment]
Hi kniteen, i would love to work on this!!!

**Comment by Niketiiitd** [comment]
Hi kniteen, i would love to work on this!!!

**Comment by KniteenK** [comment]
Sure , assigned it you

**Comment by Niketiiitd** [comment]
Hey i have done the changes in my branch and opened for merge request please reiew and let me know
